Lazy index
meilisearch/meilisearch-swift pull request #193
Opened 2021-09-20 16:17 UTC by bidoubiwa

2021-09-22 15:36 UTC, alallema reviewed
🔥 🔥 🔥 🎉 🎉 🎉 
So great @bidoubiwa!

2021-09-22 15:36 UTC, alallema commented on Sources/MeiliSearch/Indexes.swift
> +   - parameter documents:  The documents to add in MeiliSearch.
```suggestion
   - parameter documents:  The documents to update in MeiliSearch.
```

2021-09-22 15:36 UTC, alallema commented on Sources/MeiliSearch/Indexes.swift
> +   List the all Documents.
```suggestion
   List all Documents.
```

2021-09-22 15:36 UTC, alallema commented on Sources/MeiliSearch/Indexes.swift
> +   - parameter limit:      Limit the size of the query.
It's not limit it's an option

2021-09-22 15:36 UTC, alallema commented on Sources/MeiliSearch/Indexes.swift
> +   - parameter identifier: The document identifier for the Document to be found.
It's not identifier it's document Id

2021-09-22 15:36 UTC, alallema commented on Sources/MeiliSearch/Indexes.swift
> +   Delete a Document on the index based on the provided document identifier.
```suggestion
   Delete a document on the index based on the provided document identifier.
```

2021-09-22 15:36 UTC, alallema commented on Sources/MeiliSearch/Indexes.swift
> +   Delete a Document on the index based on the provided document identifier.
And others

2021-09-22 15:36 UTC, alallema commented on Sources/MeiliSearch/Indexes.swift
> +   - parameter documentsIdentifiers: The array of unique identifier for the Document to be deleted.
It's documentIds

2021-09-22 15:36 UTC, alallema commented on Sources/MeiliSearch/Indexes.swift
> +   - parameter update:    The update value.
It's UpdateId

2021-09-22 15:36 UTC, alallema commented on Sources/MeiliSearch/Indexes.swift
> +   - parameter update:    The update value.
```suggestion
   Get all update status of the index.

```

2021-09-23 08:53 UTC, curquiza requested changes
This kind of feature addition 👌 🎉 

<img width="212" alt="Capture d’écran 2021-09-23 à 10 53 09" src="https://user-images.githubusercontent.com/20380692/134479497-83bf2818-5e9b-414b-a939-eafeed368b0a.png">

2021-09-23 08:53 UTC, curquiza commented on Sources/MeiliSearch/Indexes.swift
> +  // MARK: Searchable Attribute
```suggestion
  // MARK: Searchable Attributes
```

2021-09-23 08:53 UTC, curquiza commented on Sources/MeiliSearch/Indexes.swift
> +  // MARK: Displayed Attribute
```suggestion
  // MARK: Displayed Attributes
```

2021-09-23 10:13 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
>    let documents: Data = Data(contentsOf: path)
Its the most accurante since it imports the movies.json file!

2021-09-23 12:26 UTC, curquiza commented
Don't forget the `breaking-change` label?

2021-09-23 12:42 UTC, alallema approved these changes

2021-09-23 13:05 UTC, bidoubiwa commented
bors merge

2021-09-23 13:08 UTC, merged