Added public initializer for KeyParams.
meilisearch/meilisearch-swift pull request #336
Opened 2022-10-04 22:23 UTC by mannuch

# Pull Request

## Related issue
The `KeyParams` struct does not have a publicly accessible initializer. This implies that any code outside the `MeiliSearch` module cannot create a new `KeyParams` instance.

This works in direct contrast to examples laid out in the Meilisearch documentation in which it displays constructing new `KeyParams` instances to pass to the `POST /keys` endpoint, which can be seen [here](https://docs.meilisearch.com/learn/security/master_api_keys.html#creating-an-api-key), if you select Swift as the client language.

I've simply explicitly added a public initializer to the `KeyParams` struct.

2022-10-05 15:48 UTC, curquiza commented
bors try

2022-10-05 16:14 UTC, curquiza commented
Hello @mannuch 
Thanks for the PR!
Looks like there is a linter issue. Could you fix it?

2022-10-10 06:05 UTC, brunoocasali commented
Hi @mannuch thanks for your contribution!!

I would like to know if you have any tips to test this behavior, so we can prevent that from happening again in the future.

2022-10-10 06:06 UTC, brunoocasali requested changes
Thanks a lot @mannuch! As @curquiza said, we still have some linting issues. Also, I posted a comment earlier asking about how we can test this :)

2022-10-18 18:45 UTC, brunoocasali commented
Hi, @mannuch are you still interested in continuing working in this PR?

2022-10-18 19:03 UTC, mannuch commented
Yes I am! Sorry I've been busy the past couple weeks, but I will try to implement the necessary changes at the end of the week.

Thanks for your patience!

2022-10-31 14:47 UTC, brunoocasali requested changes

2022-10-31 15:55 UTC, brunoocasali commented on Sources/MeiliSearch/Model/KeyParams.swift
> +  public init(description: String? = nil, name: String? = nil, uid: String? = nil, actions: [String], indexes: [String], expiresAt: String?) {
```suggestion

  public init(description: String? = nil, name: String? = nil, uid: String? = nil, actions: [String], indexes: [String], expiresAt: String?) {
```

2022-10-31 16:03 UTC, brunoocasali commented on Sources/MeiliSearch/Model/KeyParams.swift
> +
```suggestion
  public init(description: String? = nil, name: String? = nil, uid: String? = nil, actions: [String], indexes: [String], expiresAt: String?) {
    self.description = description
    self.name = name
    self.uid = uid
    self.actions = actions
    self.indexes = indexes
    self.expiresAt = expiresAt
  }

```

2022-11-03 19:58 UTC, brunoocasali approved these changes
Thanks for contributing with Meilisearch ❤️ 

bors merge!

2022-11-03 20:02 UTC, merged

2022-11-03 20:12 UTC, brunoocasali commented
Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).