This commit renamed all the occurence of MEILISEARCH_HOST to MEILISEA…
meilisearch/meilisearch-swift pull request #340
Opened 2022-10-11 12:10 UTC by zt4ff

…RCH_URL

# Pull Request

## Related issue
Fixes #339 

## What does this PR do?
- It replace MEILISEARCH_HOST by MEILISEARCH_URL in the docker config

## PR checklist
Please check if your PR fulfils the following requirements:
- [X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-10-12 07:29 UTC, brunoocasali commented
Thanks a lot for your contribution @zt4ff :D

2022-10-12 07:39 UTC, brunoocasali requested changes

2022-10-12 07:39 UTC, brunoocasali commented on Tests/MeiliSearchIntegrationTests/Utils.swift
> +  ProcessInfo.processInfo.environment["MEILISEARCH_URL"] ?? "http://localhost:7700"
I can't comment in other places, but can you also change the name of the `host` param? It now should also be `url`.

example:
`client = try MeiliSearch(host: "http://localhost:7700", apiKey: "masterKey")` become `client = try MeiliSearch(url: "http://localhost:7700", apiKey: "masterKey")`

also, in the `code-samples.meilisearch.yml` and over the README :)

2022-10-12 07:43 UTC, brunoocasali commented on Tests/MeiliSearchIntegrationTests/Utils.swift
> +  ProcessInfo.processInfo.environment["MEILISEARCH_URL"] ?? "http://localhost:7700"
Better thinking is not the best way to forward with that. We should deprecate the current param first. Then in another PR and another release version, remove it.

2022-10-12 07:43 UTC, brunoocasali commented on Tests/MeiliSearchIntegrationTests/Utils.swift
> +  ProcessInfo.processInfo.environment["MEILISEARCH_URL"] ?? "http://localhost:7700"
So, can you "deprecate" the `host` from `MeiliSearch` param to merge this PR?

2022-10-14 11:39 UTC, brunoocasali commented on Tests/MeiliSearchIntegrationTests/Utils.swift
> +  ProcessInfo.processInfo.environment["MEILISEARCH_URL"] ?? "http://localhost:7700"
Better thinking again, we can do that later. Thanks!

2022-10-14 11:39 UTC, brunoocasali approved these changes
Thanks again for your PR!

bors merge

2022-10-14 11:44 UTC, merged

2022-10-14 11:44 UTC, brunoocasali commented
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

2022-10-14 16:59 UTC, zt4ff commented
Thanks @brunoocasali