Fix-#363 'type should be enum'
meilisearch/meilisearch-swift pull request #375
Opened 2023-03-17 15:28 UTC by Dishant10

# Pull Request

## Related issue
Fixes #363 

## What does this PR do?
Makes the type variable an enum and all the cases are made as per the issue description.
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [• ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [• ] Have you read the contributing guidelines?
- [• ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2023-03-17 21:31 UTC, brunoocasali requested changes
Hi @Dishant10, thanks for your PR!

The CI must pass in order to merge your contribution! Check the linter messages and make sure your tests are passing locally :)

2023-03-18 04:54 UTC, Dishant10 commented
@brunoocasali can you please guide me what do I have to do in order to fix the other two failing tests.
Thank you!!

2023-03-24 13:35 UTC, brunoocasali requested changes
I left some comments they may help you fix the issues!

2023-03-24 13:35 UTC, brunoocasali commented on Sources/MeiliSearch/Model/Task.swift
> +        case indexCreation
The indentation is not following the guidelines of the project. Also, you can move this enum to the bottom of the file but still inside of the scope of the `public struct Task`.

`Type` is a protected word in Swift, so you can use `TaskType` instead.

2023-03-24 13:35 UTC, brunoocasali commented on Sources/MeiliSearch/Model/Task.swift
> +        case snapshotCreation
You still have to fix these typing errors to make your tests pass:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/4116980/227534860-3161714a-2073-4e0e-9df9-e507d968c69b.png">

Example, from this:  

`XCTAssertEqual("indexCreation", task.type)` 
to this:
`XCTAssertEqual(Task.TaskType.indexCreation, task.type)`

2023-03-24 13:35 UTC, brunoocasali commented on Sources/MeiliSearch/Model/Task.swift
> +    public enum Type:Codable {
Also, there is some GithubAction annotations, please fix them:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/4116980/227535375-56d25555-9cec-4757-85e8-b5e5b0c1e1b2.png">

2023-03-25 04:56 UTC, Dishant10 commented
Thank you! @brunoocasali this will help me a lot!
I will fix these as soon as possible!
Thank you!

2023-04-28 08:10 UTC, Dishant10 commented
I also had some doubts while fixing typing issues as you mentioned in the IndexesResults.swift file.  So I want to test it locally first.

2023-04-28 19:34 UTC, brunoocasali commented
> Hii @brunoocasali I'm sorry I was away for some time. I've made some changes, how can I test and get the messages on my local before raising a PR. ? Thank you!!

Hi @Dishant10 good to see you here!

You can follow the instructions written here:
https://github.com/meilisearch/meilisearch-swift/blob/main/CONTRIBUTING.md#development-workflow

2023-08-01 04:13 UTC, brunoocasali commented
Closing due to inactivity!

2023-08-01 04:13 UTC, closed without merging