Move run-tests.sh to a distinct folder
meilisearch/meilisearch-swift pull request #70
Opened 2020-10-10 13:28 UTC by ppamorim

Move this script to a separated folder to keep the project less clogged.

2020-10-10 14:26 UTC, ppamorim commented
bors try

2020-10-12 08:42 UTC, bidoubiwa approved these changes

2020-10-12 09:03 UTC, curquiza requested changes
Could you update the CONTRIBUTING.md accordingly, please? 🙂

2020-10-12 12:25 UTC, ppamorim commented
@curquiza Done, could you please review it again?

2020-10-12 13:00 UTC, curquiza requested changes

2020-10-12 13:00 UTC, curquiza commented on CONTRIBUTING.md
> +If you want to run the linter `swiftlint`:
```suggestion
If you want to run the linter [`swiftlint`](https://github.com/realm/SwiftLint):
```

2020-10-12 13:30 UTC, curquiza commented
bors try

2020-10-12 13:40 UTC, curquiza approved these changes

2020-10-12 13:40 UTC, curquiza commented
bors merge

2020-10-12 13:45 UTC, merged