Add dump support
meilisearch/meilisearch-swift pull request #72
Opened 2020-10-10 15:00 UTC by ppamorim

Add dumps route support, unit and integration tests included.

2020-10-10 16:16 UTC, ppamorim commented
bors try

2020-10-12 15:31 UTC, curquiza requested changes
Thanks for this work 🙂
Tiny changes requested

2020-10-12 15:31 UTC, curquiza commented on Sources/MeiliSearch/Client.swift
> +     If the request was sucessful or `Error` if a failure occured.
```suggestion
     If the request was successful or `Error` if a failure occurred.
```

2020-10-12 15:31 UTC, curquiza commented on Sources/MeiliSearch/Client.swift
> +     value that can be used later to check the status of the Dump.
```suggestion
     value that can be used later to check the status of the dump.
```

2020-10-12 15:31 UTC, curquiza commented on Sources/MeiliSearch/Client.swift
> +     `Dump.Status.dumpProcessFailed`: An error occured during dump process, and the task was aborted.
```suggestion
     `Dump.Status.dumpProcessFailed`: An error occurred during the dump process, and the task was aborted.
```

2020-10-12 15:31 UTC, curquiza commented on Sources/MeiliSearch/Client.swift
> +     If the request was sucessful or `Error` if a failure occured.
```suggestion
     If the request was successful or `Error` if a failure occurred.
```

2020-10-12 15:31 UTC, curquiza commented on Sources/MeiliSearch/Dumps.swift
> + Settings is a list of all the customization possible for an index.
Not the right info 😉

2020-10-12 15:31 UTC, curquiza commented on Tests/MeiliSearchIntegrationTests/DumpsTests.swift
> +                XCTFail("Failed to request dump creation")
Weird indentation

2020-10-12 15:31 UTC, curquiza commented on Tests/MeiliSearchIntegrationTests/DumpsTests.swift
> +                        XCTFail("Failed to request dump creation")
Weird indentation

2020-10-12 16:54 UTC, ppamorim commented
@curquiza All fixed! :)

2020-10-12 17:54 UTC, ppamorim commented
bors try

2020-10-13 13:22 UTC, eskombro submitted a review, later dismissed
👌 Thanks @ppamorim for this implementation!

2020-10-13 14:10 UTC, bidoubiwa reviewed
Hey ! Thanks a lot for this PR :) I have a few questions of implementation that I do not understand.

2020-10-13 14:10 UTC, bidoubiwa commented on Sources/MeiliSearch/Model/Dump.swift
> +            }
What is this for? Why do we need an enum for that? 

This seems like a lot of code for something that is just a string
```
case processing
        case dumpProcessFailed
        case done
```

2020-10-14 01:03 UTC, ppamorim commented on Sources/MeiliSearch/Dumps.swift
> +                }
This parses the data that comes from the server if the decode fails an error `Swift.Error` returns in the closure.

2020-10-14 08:30 UTC, bidoubiwa approved these changes

2020-10-14 13:42 UTC, curquiza commented
bors try

2020-10-14 17:30 UTC, curquiza commented
bors try

2020-10-15 07:40 UTC, curquiza commented
bors try

2020-10-15 07:51 UTC, curquiza submitted a review, later dismissed

2020-10-15 07:52 UTC, curquiza commented
bors merge

2020-10-15 08:28 UTC, curquiza commented
@ppamorim there is random fail with dumps in the tests -> https://github.com/meilisearch/meilisearch-swift/runs/1257819347

2020-10-15 15:45 UTC, bidoubiwa approved these changes

2020-10-15 15:55 UTC, curquiza requested changes
Sorry not to have seen this before... 😅

2020-10-15 15:55 UTC, curquiza commented on Tests/MeiliSearchUnitTests/DumpsTests.swift
> +        let expectation = XCTestExpectation(description: "Get settings")
```suggestion
        let expectation = XCTestExpectation(description: "Create dump")
```

2020-10-15 15:55 UTC, curquiza commented on Tests/MeiliSearchUnitTests/DumpsTests.swift
> +        let expectation = XCTestExpectation(description: "Get settings")
```suggestion
        let expectation = XCTestExpectation(description: "Get the dump status")
```

2020-10-15 15:55 UTC, curquiza commented on Tests/MeiliSearchUnitTests/DumpsTests.swift
> +                XCTFail("Failed to get settings")
```suggestion
                XCTFail("Failed to create dump")
```

2020-10-15 15:55 UTC, curquiza commented on Tests/MeiliSearchUnitTests/DumpsTests.swift
> +                XCTFail("Failed to get settings")
```suggestion
                XCTFail("Failed to get the dump status")
```

2020-10-15 16:01 UTC, curquiza submitted a review, later dismissed

2020-10-15 16:08 UTC, curquiza commented
bors merge

2020-10-15 16:18 UTC, curquiza commented
tests still failing:
```
/Users/runner/work/meilisearch-swift/meilisearch-swift/Tests/MeiliSearchIntegrationTests/DumpsTests.swift:57: error: -[MeiliSearchIntegrationTests.DumpsTests testGetDumpStatus] : failed - Failed to request dump creation
/Users/runner/work/meilisearch-swift/meilisearch-swift/Tests/MeiliSearchIntegrationTests/DumpsTests.swift:61: error: -[MeiliSearchIntegrationTests.DumpsTests testGetDumpStatus] : Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "Request dump creation".
Test Case '-[MeiliSearchIntegrationTests.DumpsTests testGetDumpStatus]' failed (10.867 seconds).
Test Suite 'DumpsTests' failed at 2020-10-15 16:12:53.560.
	 Executed 2 tests, with 2 failures (0 unexpected) in 10.872 (10.872) seconds
```

2020-10-15 16:24 UTC, ppamorim commented
@curquiza Tests are locally working, I am not sure why bors failed.

2020-10-15 22:25 UTC, ppamorim commented
bors merge

2020-10-15 23:31 UTC, ppamorim commented
bors try

2020-10-16 00:06 UTC, ppamorim commented
bors try

2020-10-16 00:52 UTC, ppamorim commented
@curquiza it was the test to create the dump running in less than 1s. I think the first test could be removed.

2020-10-16 09:15 UTC, ppamorim commented
@curquiza I think we should remove the first test. The second test does the same.

2020-10-19 19:58 UTC, ppamorim commented
bors try

2020-10-20 12:36 UTC, curquiza reviewed
Small naming change 🙂

2020-10-20 12:36 UTC, curquiza commented on Tests/MeiliSearchIntegrationTests/DumpsTests.swift
> +    func testCreateDumpGetDumpStatus() {
```suggestion
    func testCreateAndGetDump() {
```

2020-10-20 12:36 UTC, curquiza commented on Tests/MeiliSearchIntegrationTests/DumpsTests.swift
> +        ("testCreateDumpGetDumpStatus", testCreateDumpGetDumpStatus)
```suggestion
        ("testCreateAndGetDump", testCreateAndGetDump)
```

2020-10-23 12:17 UTC, ppamorim commented
bors try

2020-10-23 12:51 UTC, curquiza approved these changes

2020-10-23 12:52 UTC, curquiza commented
bors merge

2020-10-23 12:54 UTC, merged

2020-10-23 14:16 UTC, ppamorim commented
@curquiza Thank you very much!